import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

// Created by admin when approving an NGO application.
// Stores login credentials and whether the email was sent to the org.
export const NgoVerification = sequelize.define('NgoVerification', {
	id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },

	application_id: { type: DataTypes.INTEGER, allowNull: false, unique: true },
	user_id:        { type: DataTypes.INTEGER, allowNull: false, unique: true },

	username:       { type: DataTypes.STRING(100), allowNull: false, unique: true },
	// Stored plain for admin display in the NGO Registry table — generated by admin
	password_plain: { type: DataTypes.STRING(255), allowNull: true },

	email_sent: { type: DataTypes.BOOLEAN, defaultValue: false },

}, { tableName: 'ngo_verifications', underscored: true });
